CHANGELOG.md, README.md, index.js, package-lock.json, package.json, src/cookies.ts, src/intercept.ts, src/localSessionStorage.ts, src/utils/utils.ts, test-e2e/apps/storage.html, test-e2e/features/intercept.feature, test-e2e/features/storage.feature, test-e2e/memory/index.ts, test-e2e/page_object/index.ts, test-e2e/support/server.ts, test-e2e/webui.ts
added support of multiple events for taking screenshots
=> added interceptor steps

CHANGELOG.md, package-lock.json, package.json, src/actions.ts, src/utils/utils.ts, test-e2e/apps/actions.html, test-e2e/features/actions.feature, test-e2e/page_object/index.ts
https://github.com/qavajs/steps-playwright/issues/66
=> add _I click {string} coordinates in {string}_ step

.gitignore, CHANGELOG.md, package-lock.json, package.json, src/actions.ts, test-e2e/features/actions.feature, test-e2e/step-definitions/index.ts
=> implement _I set window size {string}_ step

.github/pull_request_template.md, CHANGELOG.md, package-lock.json, package.json, src/waits.ts, test-e2e/features/waits.feature, test-e2e/webui.ts
Added I wait until {string} css property of {string} {playwrightValueWait} {string}( ){playwrightTimeout}_ step
=> added I wait for css property

CHANGELOG.md, package-lock.json, package.json
=> release 0.37.0

.github/workflows/pull-request.yml, CHANGELOG.md, package-lock.json, src/actions.ts, test-e2e/features/actions.feature
- [✓] Updated the CHANGELOG.md.
- [✓] Checked that there aren't other open pull requests for the same issue/update.
- [✓] Checked that your contribution follows the project's contribution guidelines.
- [✓] Added corresponding unit/E2E tests
- [✓] Unit and E2E pass
I added "I close current tab step"
[Add a step: I close current tab #85](https://github.com/qavajs/steps-playwright/issues/85)
=> add I close current tab step

package-lock.json, package.json
Chore: updated playwright dependency
=> updated playwright version

CHANGELOG.md, src/actions.ts, src/hooks.ts
changed behavior of _I switch to {string} window_ step (now it is wai…t for window existence)
fixed getting of electron context
=> changed behavior of _I switch to {string} window_ step

CHANGELOG.md, package.json, src/actions.ts
---
Thank you for your contribution!
=> Replace type to fill

package-lock.json, package.json
=> updated validation dependency

.github/workflows/npm-publish.yml, .github/workflows/pull-request.yml, CHANGELOG.md, package.json, src/validations.ts, src/waits.ts, test-e2e/features/validations.feature, test-e2e/features/waits.feature, test-e2e/webui.ts
=> added value wait and expect steps

CHANGELOG.md, package-lock.json, package.json
=> release 0.45.0

CHANGELOG.md, package-lock.json, package.json
=> release 0.46.0

CHANGELOG.md, package-lock.json, package.json, tsconfig.json
updated compile target to ES2017
=> updated compile target

CHANGELOG.md, package-lock.json, package.json
=> updated dependencies

.github/pull_request_template.md, .github/workflows/npm-publish.yml, .github/workflows/pull-request.yml, CHANGELOG.md, package-lock.json, package.json, src/utils/tracingManager.ts
added error handling during trace attach
=> added error handling during trace attach

CHANGELOG.md, package-lock.json, package.json, src/defaultTimeouts.ts, src/waits.ts, test-e2e/apps/waits.html, test-e2e/features/waits.feature, test-e2e/page_object/index.ts, tsconfig.json
=> add refresh page until text step

CHANGELOG.md, package-lock.json, package.json
=> update playwright to 1.45.0

CHANGELOG.md, index.d.ts, package-lock.json, package.json, src/IQavajsPlaywrightConfig.ts, src/defaultTimeouts.ts, src/waits.ts, test-e2e/apps/waits.html, test-e2e/features/waits.feature, test-e2e/page_object/index.ts, utils.d.ts
[Please link any related issues or bug reports that this PR will address.](https://github.com/qavajs/steps-playwright/issues/125)
=> click until text step

CHANGELOG.md, package-lock.json, package.json, po.d.ts, po.js, src/waits.ts, test-e2e/page_object/index.ts, test-e2e/webui.ts, test/poImport.spec.ts
=> include page objects into step bundle

CHANGELOG.md, package-lock.json, package.json, src/IQavajsPlaywrightConfig.ts, src/waits.ts, test-e2e/apps/waits.html, test-e2e/features/waits.feature, test-e2e/page_object/index.ts, test-e2e/step-definitions/index.ts, test-e2e/webui.ts
=> Add "I wait for network idle for {int} ms" step

CHANGELOG.md, package-lock.json, package.json, src/actions.ts
=> improved _I scroll until_ steps to use same locator

package-lock.json, package.json, src/actions.ts, src/cookies.ts, src/execute.ts, src/intercept.ts, src/localSessionStorage.ts, src/memory.ts, src/mock.ts, src/mouseActions.ts, src/poDefine.ts, src/validations.ts, src/waits.ts, test-e2e/step-definitions/index.ts
=> updated dependency to qavajs core

CHANGELOG.md, package-lock.json, package.json, src/pageObject.ts, test-e2e/features/pageObject.feature, test-e2e/page_object/index.ts
=> added `locator.as` method to define top level components (like pages)

CHANGELOG.md, package-lock.json, package.json, src/pageObject.ts, src/poDefine.ts, test-e2e/webui.ts
=> added capability to pass page object as instance

CHANGELOG.md, package-lock.json, package.json, src/validations.ts, test-e2e/features/validations.feature
added `I expect {value} css property of every element in {playwrightLocator} collection {validation} {value}` step
=> added `I expect {value} css property of every element in {playwrightLocator} collection {validation} {value}` step

CHANGELOG.md, package-lock.json, package.json, tsconfig.json
=> added source maps

CHANGELOG.md, README.md, package-lock.json, package.json, src/pageObject.ts
=> added selector logging

CHANGELOG.md, package-lock.json, package.json
=> updated playwright dependency

CHANGELOG.md, package-lock.json, package.json, src/pageObject.ts, test-e2e/features/dialog.feature, test-e2e/features/pageObject.feature, test-e2e/page_object/index.ts
=> Added capability to provide _defaultResolver_ to define default logic to identify element

CHANGELOG.md, package-lock.json, package.json, src/conditionWait.ts, src/types.ts, src/utils/utils.ts, test-e2e/features/pollValidations.feature, tsconfig.json
added capability to perform soft validation of element condition validations
=> added capability to perform soft validation of element condition validations
